# Generated by Django 5.2.4 on 2025-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardStockManageApp', '0002_alter_card_image_url_alter_card_name_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypricehistory',
            name='online_lowest_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='sell_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
