# Generated by Django 5.2.4 on 2025-09-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardStockManageApp', '0003_dailypricehistory_online_lowest_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='card',
            name='data_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('data_number__isnull', False)), fields=('game', 'set', 'data_number'), name='unique_card_with_data_number'),
        ),
    ]
